In [2]:
import numpy as np

In [7]:
patients_data = np.array([ 
[45, 80, 200, 120], 
[60, 90, 240, 140], 
[30, 70, 180, 110], 
[50, 85, 220, 130], 
[65, 95, 260, 150] 
])

In [8]:

#Q1
print("Shape:", patients_data.shape)
print("Number of patients:", patients_data.shape[0])
print("Number of features:", patients_data.shape[1])


Shape: (5, 4)
Number of patients: 5
Number of features: 4


In [9]:
# Q2
print("First patient:", patients_data[0])
print("All ages:", patients_data[:, 0])
print("All blood pressure:", patients_data[:, 3])


First patient: [ 45  80 200 120]
All ages: [45 60 30 50 65]
All blood pressure: [120 140 110 130 150]


In [10]:
# Q3
print("Average age:", np.mean(patients_data[:, 0]))
print("Max heart rate:", np.max(patients_data[:, 1]))
print("Min cholesterol:", np.min(patients_data[:, 2]))


Average age: 50.0
Max heart rate: 95
Min cholesterol: 180


In [12]:
# Part 2: Filtering & Conditions
# Q4
high = patients_data[patients_data[:, 3] > 130]
print("High BP patients:", high)

High BP patients: [[ 60  90 240 140]
 [ 65  95 260 150]]


In [13]:
# Q5
highchol = patients_data[patients_data[:, 2] >= 240]
print("High Cholesterol patients:", highchol)


High Cholesterol patients: [[ 60  90 240 140]
 [ 65  95 260 150]]


In [14]:
# Q6
older = patients_data[patients_data[:, 0] > 50]
print("Patients older than 50:", older)

Patients older than 50: [[ 60  90 240 140]
 [ 65  95 260 150]]


In [17]:
# Part 3: Thinking Like a Data Scientist
# Q7
highrisk = patients_data[
    (patients_data[:, 3] > 140) |
    (patients_data[:, 2] > 240)
]
highrisk

array([[ 65,  95, 260, 150]])

In [18]:
# Q8
under50 = patients_data[patients_data[:, 0] < 50]
above50 = patients_data[patients_data[:, 0] >= 50]
print("Avrage HR < 50:", np.mean(under50[:, 1]))
print("Avrage HR >= 50:", np.mean(above50[:, 1]))

Avrage HR < 50: 75.0
Avrage HR >= 50: 90.0


In [21]:
# Q9
highestbp = np.max(patients_data[:, 3])
lowesthr = np.min(patients_data[:, 1])
print("Highest BP patient:", highestbp)
print("Lowest HR patient:", lowesthr)


Highest BP patient: 150
Lowest HR patient: 70


In [23]:
# Part 4: 
# Q10
ages = patients_data[:, 0]
bp = patients_data[:, 3]
print("ages:", ages)
print("Blood Pressure:", bp)
print("older patient tend to have higher presssure in this data")


ages: [45 60 30 50 65]
Blood Pressure: [120 140 110 130 150]
older patient tend to have higher presssure in this data
