In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("alyahmedts13/reddit-sentiment-analysis-dataset-for-nlp-projects")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'reddit-sentiment-analysis-dataset-for-nlp-projects' dataset.
Path to dataset files: /kaggle/input/reddit-sentiment-analysis-dataset-for-nlp-projects


In [ ]:
import pandas as pd
import os
data_path = '/root/.cache/kagglehub/datasets/alyahmedts13/reddit-sentiment-analysis-dataset-for-nlp-projects/versions/1'
file_name = 'reddit_artist_posts_sentiment.csv'
df = pd.read_csv(os.path.join(data_path, file_name))

print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31948 entries, 0 to 31947
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    31948 non-null  object
 1   label   31948 non-null  object
dtypes: object(2)
memory usage: 499.3+ KB
None
                                                text     label
0  pitchfork track review: taylor swift’s “actual...  negative
1  taylor swift has regained the masters of her f...  positive
2  pitchfork review: taylor swift - the life of a...   neutral
3                  taylor swift announced engagement   neutral
4  taylor swift - the fate of ophelia (official m...   neutral


In [ ]:
import re
from sklearn.model_selection import train_test_split

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text

df['clean_text'] = df['text'].apply(clean_text)

X = df['clean_text']
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# 1. Bag of Words (BoW)
bow_vectorizer = CountVectorizer(stop_words='english', max_features=5000)
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

# 2. TF-IDF
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [ ]:

vocab_bow = bow_vectorizer.get_feature_names_out()
print(f"عدد الكلمات المستخرجة في BoW: {len(vocab_bow)}")

vocab_tfidf = tfidf_vectorizer.get_feature_names_out()
print(f"عدد الكلمات المستخرجة في TF-IDF: {len(vocab_tfidf)}")

عدد الكلمات المستخرجة في BoW: 5000
عدد الكلمات المستخرجة في TF-IDF: 5000


In [ ]:
import numpy as np

def calculate_tfidf_manually(tf, idf):
    # القانون: TF * IDF
    return tf * idf

# مثال:
# لو كان تكرار كلمة في مستند هو 0.5 (TF)
# وقيمة الـ IDF هي 1.3
tf_value = 0.5
idf_value = 1.3

tfidf_score = calculate_tfidf_manually(tf_value, idf_value)
print(f"قيمة الـ TF-IDF المحسوبة يدوياً: {tfidf_score}")

قيمة الـ TF-IDF المحسوبة يدوياً: 0.65


In [ ]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf_vectorizer.fit_transform(df['text'])

first_value = tfidf_matrix[0, 0]
print(f"قيمة الـ TF-IDF الناتجة برمجياً: {first_value:.4f}")

قيمة الـ TF-IDF الناتجة برمجياً: 0.0000


In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

sample_texts = df['text'].head(5)

cv = CountVectorizer(stop_words='english', max_features=10)
bow_matrix = cv.fit_transform(sample_texts)

bow_df = pd.DataFrame(bow_matrix.toarray(), columns=cv.get_feature_names_out())

print(" (BoW):")
print(bow_df)

 (BoW):
   actually  albums  engagement  fate  life  masters  pitchfork  review  \
0         2       0           0     0     0        0          1       1   
1         0       1           0     0     0        1          0       0   
2         0       0           0     0     1        0          1       1   
3         0       0           1     0     0        0          0       0   
4         0       0           0     1     0        0          0       0   

   swift  taylor  
0      1       1  
1      1       1  
2      1       1  
3      1       1  
4      1       1  


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
tfidf = TfidfVectorizer(stop_words=None)
tfidf_matrix = tfidf.fit_transform(df['text'].head(100)) # نأخذ عينة لتسريع المعالجة

tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf.get_feature_names_out())

feature_names = tfidf.get_feature_names_out()

try:
    print(f"وزن كلمة 'the' (شائعة): {tfidf_df['the'].mean():.6f}")
    print(f"وزن كلمة 'taylor' (مميزة): {tfidf_df['taylor'].mean():.6f}")
except KeyError:
    print("الكلمات غير موجودة في العينة، جرب تغيير الكلمات.")

وزن كلمة 'the' (شائعة): 0.088006
وزن كلمة 'taylor' (مميزة): 0.112471


In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("alyahmedts13/reddit-sentiment-analysis-dataset-for-nlp-projects")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'reddit-sentiment-analysis-dataset-for-nlp-projects' dataset.
Path to dataset files: /kaggle/input/reddit-sentiment-analysis-dataset-for-nlp-projects


In [ ]:
import pandas as pd
import numpy as np

import nltk
import re

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [ ]:
import kagglehub

path = kagglehub.dataset_download(
    "alyahmedts13/reddit-sentiment-analysis-dataset-for-nlp-projects"
)

print(path)

Using Colab cache for faster access to the 'reddit-sentiment-analysis-dataset-for-nlp-projects' dataset.
/kaggle/input/reddit-sentiment-analysis-dataset-for-nlp-projects


In [ ]:
import os

print(os.listdir(path))

['reddit_artist_posts_sentiment.csv']


In [ ]:
import pandas as pd

df = pd.read_csv(path + "/reddit_artist_posts_sentiment.csv")

In [ ]:
print(df.columns)

Index(['text', 'label'], dtype='object')


In [ ]:
print(df.columns)

Index(['text', 'label'], dtype='object')


In [ ]:
y = df["label"]

In [ ]:
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download("stopwords")
nltk.download("wordnet")

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):

    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", "", text)

    # Remove punctuation and numbers
    text = re.sub(r"[^a-zA-Z\s]", "", text)

    # Tokenization
    tokens = text.split()

    # Stopwords Removal
    tokens = [word for word in tokens if word not in stop_words]

    # Lemmatization
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return " ".join(tokens)

df["clean_text"] = df["text"].apply(preprocess_text)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer(max_features=5000)

X_bow = bow.fit_transform(df["clean_text"])

y = df["label"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_bow,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
from sklearn.naive_bayes import MultinomialNB

nb_bow = MultinomialNB()

nb_bow.fit(X_train, y_train)

pred_bow = nb_bow.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print("===== Bag of Words =====")

print("Accuracy:", accuracy_score(y_test, pred_bow))

print(classification_report(y_test, pred_bow))

print(confusion_matrix(y_test, pred_bow))

===== Bag of Words =====
Accuracy: 0.7234741784037558
              precision    recall  f1-score   support

    negative       0.49      0.53      0.51       679
     neutral       0.81      0.79      0.80      3946
    positive       0.64      0.66      0.65      1765

    accuracy                           0.72      6390
   macro avg       0.65      0.66      0.65      6390
weighted avg       0.73      0.72      0.73      6390

[[ 362  226   91]
 [ 291 3103  552]
 [  84  523 1158]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X_tfidf = tfidf.fit_transform(df["clean_text"])

In [ ]:
nb_tfidf = MultinomialNB()

nb_tfidf.fit(X_train, y_train)

pred_tfidf = nb_tfidf.predict(X_test)

In [ ]:
print("===== TF-IDF =====")

print("Accuracy:", accuracy_score(y_test, pred_tfidf))

print(classification_report(y_test, pred_tfidf))

print(confusion_matrix(y_test, pred_tfidf))

===== TF-IDF =====
Accuracy: 0.7234741784037558
              precision    recall  f1-score   support

    negative       0.49      0.53      0.51       679
     neutral       0.81      0.79      0.80      3946
    positive       0.64      0.66      0.65      1765

    accuracy                           0.72      6390
   macro avg       0.65      0.66      0.65      6390
weighted avg       0.73      0.72      0.73      6390

[[ 362  226   91]
 [ 291 3103  552]
 [  84  523 1158]]


In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test, pred_tfidf)

print("="*50)
print("TF-IDF + Multinomial Naive Bayes")
print("="*50)

print(f"Accuracy: {accuracy:.4f}\n")

print("Classification Report:")
print(classification_report(y_test, pred_tfidf))

print("Confusion Matrix:")
print(confusion_matrix(y_test, pred_tfidf))

TF-IDF + Multinomial Naive Bayes
Accuracy: 0.7235

Classification Report:
              precision    recall  f1-score   support

    negative       0.49      0.53      0.51       679
     neutral       0.81      0.79      0.80      3946
    positive       0.64      0.66      0.65      1765

    accuracy                           0.72      6390
   macro avg       0.65      0.66      0.65      6390
weighted avg       0.73      0.72      0.73      6390

Confusion Matrix:
[[ 362  226   91]
 [ 291 3103  552]
 [  84  523 1158]]
